export const ToolsActionTypes = {
    LIST_LOAD_START: "LIST_LOAD_START",
    LIST_LOAD_SUCCESS: "LIST_LOAD_SUCCESS",
    LIST_LOAD_ERROR: "LIST_LOAD_ERROR",

    DETAIL_LOAD_START: "DETAIL_LOAD_START",
    DETAIL_LOAD_SUCCESS: "DETAIL_LOAD_SUCCESS",
    DETAIL_LOAD_ERROR: "DETAIL_LOAD_ERROR",
    DETAIL_CLEAR: "DETAIL_CLEAR"
} as const;