export const ToolsActionTypes = {
    LIST_LOAD_START: "LIST_LOAD_START",
    LIST_LOAD_SUCCESS: "LIST_LOAD_SUCCESS",
    LIST_LOAD_ERROR: "LIST_LOAD_ERROR",

    DETAIL_LOAD_START: "DETAIL_LOAD_START",
    DETAIL_LOAD_SUCCESS: "DETAIL_LOAD_SUCCESS",
    DETAIL_LOAD_ERROR: "DETAIL_LOAD_ERROR",
    DETAIL_CLEAR: "DETAIL_CLEAR",

    MUTATION_START: "MUTATION_START",
    MUTATION_ERROR: "MUTATION_ERROR",
    MUTATION_CLEAR: "MUTATION_CLEAR",

    CREATE_SUCCESS: "CREATE_SUCCESS",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    DELETE_SUCCESS: "DELETE_SUCCESS"
} as const;